apiVersion: v1
kind: Service
metadata:
  name: patos-api
  labels:
    app.kubernetes.io/name: patos-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: patos-api
  ports:
    - name: http
      port: 2000
      targetPort: http
